name: package.yml
on: [ push ]
jobs:
  build-executables:
    name: 'Build Executables'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Setup Java 18'
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: 'Build Executable'
        run: |
          ./gradlew package
      - name: 'Upload Build Artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-${{ matrix.os }}
          path: ./release-builds
  publish-executables:
    name: 'Publish Executables'
    runs-on: ubuntu-latest
    needs: build-executables
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Download Build Artifacts (Linux)'
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts-ubuntu-latest
          path: ./release-builds/linux
      - name: 'Download Build Artifacts (Windows)'
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts-windows-latest
          path: ./release-builds/windows
      - name: 'Download Build Artifacts (MacOS)'
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts-macos-latest
          path: ./release-builds/macos
      - name: 'Set Version Number'
        run: |
          echo "VERSION=$(./gradlew properties -q | grep "version: " | awk '{print $2}')" >> $GITHUB_ENV
      - name: 'Debug'
        run: |
          ls -la
      - name: 'Create Linux Archive'
        run: |
          zip -r StarMade-Launcher_Linux.zip ./release-builds/linux
      - name: 'Create Windows Archive'
        run: |
          zip -r StarMade-Launcher_Windows.zip ./release-builds/windows
      - name: 'Create MacOS Archive'
        run: |
          zip -r StarMade-Launcher_MacOS.zip ./release-builds/macos
      - name: 'Publish Linux Executable'
        id: publish-linux
        uses: actions/upload-artifact@v2-preview
        with:
          name: StarMade-Launcher (Linux)
          path: StarMade-Launcher_Linux.zip
      - name: 'Publish Windows Executable'
        id: publish-windows
        uses: actions/upload-artifact@v2-preview
        with:
          name: StarMade-Launcher (Windows)
          path: StarMade-Launcher_Windows.zip
      - name: 'Publish MacOS Executable'
        id: publish-macos
        uses: actions/upload-artifact@v2-preview
        with:
          name: StarMade-Launcher (MacOS)
          path: StarMade-Launcher_MacOS.zip
      - name: 'Upload Release Asset (Linux)'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.publish-linux.outputs.upload_url }}
          asset_path: StarMade-Launcher_Linux.zip
          asset_name: StarMade Launcher (Linux)
          asset_content_type: application/zip
      - name: 'Upload Release Asset (Windows)'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.publish-windows.outputs.upload_url }}
          asset_path: StarMade-Launcher_Windows.zip
          asset_name: StarMade Launcher (Windows)
          asset_content_type: application/zip
      - name: 'Upload Release Asset (MacOS)'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.publish-macos.outputs.upload_url }}
          asset_path: StarMade-Launcher_MacOS.zip
          asset_name: StarMade Launcher (MacOS)
          asset_content_type: application/zip