name: Build and Package StarMade Launcher

on:
    workflow_dispatch:

jobs:
    build-jar:
        name: Build JAR
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v3
            
            - name: Set up JDK 23
              uses: actions/setup-java@v3
              with:
                  java-version: '23'
                  distribution: 'temurin'
            
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            
            - name: Build with Gradle
              run: ./gradlew shadowJar
            
            - name: Upload JAR
              uses: actions/upload-artifact@v3
              with:
                  name: starmade-launcher-jar
                  path: build/libs/StarMade-Launcher.jar
    
    package-windows:
        needs: build-jar
        runs-on: windows-latest
        
        steps:
            - uses: actions/checkout@v3
            
            - name: Download JAR
              uses: actions/download-artifact@v3
              with:
                  name: starmade-launcher-jar
                  path: native-packages/windows/data
            
            - name: Setup MinGW
              uses: egor-tensin/setup-mingw@v2
            
            - name: Create native folder
              run: mkdir -p src/main/native
            
            - name: Copy unified launcher code
              run: |
                  mkdir -p src/main/native
                  copy src\main\c\starmade_launcher.c src\main\native\starmade_launcher.c
            
            - name: Compile Windows launcher
              run: |
                  cd src/main/native
                  gcc -o StarMade-Launcher.exe starmade_launcher.c -mwindows -lshlwapi
            
            - name: Set icon with Resource Hacker
              run: |
                  curl -L -o reshacker.exe http://www.angusj.com/resourcehacker/resource_hacker.zip
                  unzip reshacker.exe
                  ResourceHacker.exe -open src/main/native/StarMade-Launcher.exe -save src/main/native/StarMade-Launcher.exe -action addoverwrite -res src/main/resources/starmade.ico -mask ICONGROUP,MAINICON,
            
            - name: Package Windows distribution
              run: |
                  mkdir -p native-packages/windows/package
                  copy src\main\native\StarMade-Launcher.exe native-packages\windows\package\
                  copy native-packages\windows\data\* native-packages\windows\package\
                  copy StarMade-dedicated-server-windows.bat native-packages\windows\package\
            
            - name: Create ZIP archive
              run: |
                  cd native-packages/windows/package
                  7z a ../StarMade-Launcher-Windows.zip *
            
            - name: Upload Windows package
              uses: actions/upload-artifact@v3
              with:
                  name: starmade-launcher-windows
                  path: native-packages/windows/StarMade-Launcher-Windows.zip
    
    package-macos:
        needs: build-jar
        runs-on: macos-latest
        
        steps:
            -   uses: actions/checkout@v3
            
            -   name: Download JAR
                uses: actions/download-artifact@v3
                with:
                    name: starmade-launcher-jar
                    path: native-packages/macos/StarMade-Launcher.app/Contents/Resources/
            
            -   name: Create app bundle structure
                run: |
                    mkdir -p "native-packages/macos/StarMade-Launcher.app/Contents/MacOS"
                    mkdir -p "native-packages/macos/StarMade-Launcher.app/Contents/Resources"
            
            -   name: Create native folder
                run: mkdir -p src/main/native
            
            -   name: Copy unified launcher code
                run: |
                    mkdir -p src/main/native
                    cp src/main/c/starmade_launcher.c src/main/native/starmade_launcher.c
            
            -   name: Compile macOS launcher
                run: |
                    cd src/main/native
                    gcc -o StarMade-Launcher starmade_launcher.c -framework CoreFoundation
            
            -   name: Create Info.plist
                run: |
                    cat > "native-packages/macos/StarMade-Launcher.app/Contents/Info.plist" << EOF
                    <?xml version="1.0" encoding="UTF-8"?>
                    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
                    <plist version="1.0">
                    <dict>
                        <key>CFBundleExecutable</key>
                        <string>StarMade-Launcher</string>
                        <key>CFBundleIconFile</key>
                        <string>AppIcon</string>
                        <key>CFBundleIdentifier</key>
                        <string>org.starmade.launcher</string>
                        <key>CFBundleInfoDictionaryVersion</key>
                        <string>6.0</string>
                        <key>CFBundleName</key>
                        <string>StarMade Launcher</string>
                        <key>CFBundlePackageType</key>
                        <string>APPL</string>
                        <key>CFBundleShortVersionString</key>
                        <string>3.3.0</string>
                        <key>CFBundleVersion</key>
                        <string>3.3.0</string>
                        <key>NSHighResolutionCapable</key>
                        <true/>
                    </dict>
                    </plist>
                    EOF
            
            -   name: Copy native launcher
                run: |
                    cp src/main/native/StarMade-Launcher "native-packages/macos/StarMade-Launcher.app/Contents/MacOS/"
                    chmod +x "native-packages/macos/StarMade-Launcher.app/Contents/MacOS/StarMade-Launcher"
            
            -   name: Convert icon
                run: |
                    cp src/main/resources/starmade.icns "native-packages/macos/StarMade-Launcher.app/Contents/Resources/AppIcon.icns"
            
            -   name: Copy server script
                run: |
                    cp StarMade-dedicated-server-macos.command native-packages/macos/
                    chmod +x native-packages/macos/StarMade-dedicated-server-macos.command
            
            -   name: Create ZIP archive
                run: |
                    cd native-packages/macos
                    zip -r ../StarMade-Launcher-MacOS.zip StarMade-Launcher.app StarMade-dedicated-server-macos.command
            
            -   name: Upload macOS package
                uses: actions/upload-artifact@v3
                with:
                    name: starmade-launcher-macos
                    path: native-packages/StarMade-Launcher-MacOS.zip
    
    package-linux:
        needs: build-jar
        runs-on: ubuntu-latest
        
        steps:
            -   uses: actions/checkout@v3
            
            -   name: Download JAR
                uses: actions/download-artifact@v3
                with:
                    name: starmade-launcher-jar
                    path: native-packages/linux/starmade-launcher/
            
            -   name: Create directory structure
                run: |
                    mkdir -p native-packages/linux/starmade-launcher
            
            -   name: Create native folder
                run: mkdir -p src/main/native
            
            -   name: Copy unified launcher code
                run: |
                    mkdir -p src/main/native
                    cp src/main/c/starmade_launcher.c src/main/native/starmade_launcher.c
            
            -   name: Compile Linux launcher
                run: |
                    cd src/main/native
                    gcc -o StarMade-Launcher starmade_launcher.c
            
            -   name: Copy native launcher
                run: |
                    cp src/main/native/StarMade-Launcher native-packages/linux/starmade-launcher/
                    chmod +x native-packages/linux/starmade-launcher/StarMade-Launcher
            
            -   name: Copy server script
                run: |
                    cp StarMade-dedicated-server-linux.sh native-packages/linux/starmade-launcher/
                    chmod +x native-packages/linux/starmade-launcher/StarMade-dedicated-server-linux.sh
            
            -   name: Create Desktop Entry
                run: |
                    mkdir -p native-packages/linux/starmade-launcher/desktop
                    
                    # Create desktop entry file
                    cat > native-packages/linux/starmade-launcher/desktop/starmade-launcher.desktop << EOF
                    [Desktop Entry]
                    Type=Application
                    Name=StarMade Launcher
                    Comment=Launcher for StarMade
                    Exec=StarMade-Launcher
                    Icon=starmade-launcher
                    Terminal=false
                    Categories=Game;
                    EOF
                    
                    # Copy icon
                    mkdir -p native-packages/linux/starmade-launcher/desktop/icons
                    cp src/main/resources/starmade.png native-packages/linux/starmade-launcher/desktop/icons/starmade-launcher.png
    
            -   name: Create tar.gz archive
                run: |
                    cd native-packages/linux
                    tar -czf ../StarMade-Launcher-Linux.tar.gz starmade-launcher
            
            -   name: Upload Linux package
                uses: actions/upload-artifact@v3
                with:
                    name: starmade-launcher-linux
                    path: native-packages/StarMade-Launcher-Linux.tar.gz