name: Package
on: [ push ]
jobs:
  build-executables:
    name: 'Build ${{ matrix.os }} Executable'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Setup Java 18'
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: 'Build Executable'
        run: |
          ./gradlew package
      - name: 'Get Version Number'
        run: |
          echo "VERSION=$(./gradlew properties -q | grep "version: " | awk '{print $2}')" >> $GITHUB_ENV
      - name: 'Zip ${{ matrix.os }} Executable'
        run: |
          zip -r ${{ matrix.os }}.zip release-builds/${{ matrix.os }}
      - name: 'Publish Executable'
        uses: actions/upload-artifact@v2-preview
        with:
          name: '${{ matrix.os }}.zip'