name: 'Build and Upload'
on: workflow_dispatch
jobs:
    build-executables:
        name: 'Build Executables'
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ ubuntu-latest, windows-latest, macos-latest ]
                include:
                    -   os: 'ubuntu-latest'
                        label: 'Linux'
                    -   os: 'macos-latest'
                        label: 'MacOS'
                    -   os: 'windows-latest'
                        label: 'Windows'
        permissions:
            contents: write
            pull-requests: write
            repository-projects: write
        steps:
            -   name: 'Checkout'
                uses: actions/checkout@v4
            -   name: 'Setup Java 23'
                uses: graalvm/setup-graalvm@v1
                with:
                    java-version: 23
                    distribution: 'graalvm'
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    native-image-job-reports: 'true'
            -   name: 'Build Jar'
                run: |
                    ./gradlew package
            -   name: 'Build Executable'
                run: |
                    native-image --no-server --no-fallback --allow-incomplete-classpath --enable-url-protocols=https -jar ./StarMade-Starter.jar
            -   name: 'Rename to StarMade-Launcher (Linux)'
                if: ${{ matrix.os == 'ubuntu-latest' }}
                run: |
                    mv ./StarMade-Starter ./StarMade-Launcher
            -   name: 'Rename to StarMade-Launcher (Windows)'
                if: ${{ matrix.os == 'windows-latest' }}
                run: |
                    mv ./StarMade-Starter.exe ./StarMade-Launcher.exe
            -   name: 'Rename to StarMade-Launcher (MacOS)'
                if: ${{ matrix.os == 'macos-latest' }}
                run: |
                    mv ./StarMade-Starter ./StarMade-Launcher
            -   name: 'Mark as Executable (Linux)'
                if: ${{ matrix.os == 'ubuntu-latest' }}
                run: |
                    chmod +x ./StarMade-Launcher
            -   name: 'Mark as Executable (MacOS)'
                if: ${{ matrix.os == 'macos-latest' }}
                run: |
                    chmod +x ./StarMade-Launcher
            -   name: 'Code Signing (MacOS)'
                if: ${{ matrix.os == 'macos-latest' }}
                run: |
                    codesign --force --deep --sign - ./StarMade-Launcher
            -   name: 'Upload Build Artifacts (Linux)'
                if: ${{ matrix.os == 'ubuntu-latest' }}
                uses: actions/upload-artifact@v4
                with:
                    name: StarMade-Launcher-Linux
                    path: ./StarMade-Launcher
            -   name: 'Upload Build Artifacts (Windows)'
                if: ${{ matrix.os == 'windows-latest' }}
                uses: actions/upload-artifact@v4
                with:
                    name: StarMade-Launcher-Windows
                    path: ./StarMade-Launcher.exe
            -   name: 'Upload Build Artifacts (MacOS)'
                if: ${{ matrix.os == 'macos-latest' }}
                uses: actions/upload-artifact@v4
                with:
                    name: StarMade-Launcher-MacOS
                    path: ./StarMade-Launcher
    publish-executables:
        name: 'Publish Executables'
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            repository-projects: write
        needs: build-executables
        steps:
            -   name: 'Checkout'
                uses: actions/checkout@v4
            -   name: 'Download Build Artifacts (Linux)'
                uses: actions/download-artifact@v4
                with:
                    name: StarMade-Launcher-Linux
                    path: StarMade-Launcher-Linux/StarMade-Launcher
                    merge-multiple: true
            -   name: 'Download Build Artifacts (Windows)'
                uses: actions/download-artifact@v4
                with:
                    name: StarMade-Launcher-Windows
                    path: StarMade-Launcher-Windows/StarMade-Launcher.exe
                    merge-multiple: true
            -   name: 'Download Build Artifacts (MacOS)'
                uses: actions/download-artifact@v4
                with:
                    name: StarMade-Launcher-MacOS
                    path: StarMade-Launcher-MacOS/StarMade-Launcher
                    merge-multiple: true
            -   name: 'Set Version Number'
                run: |
                    echo "VERSION=$(./gradlew properties -q | grep "version: " | awk '{print $2}')" >> $GITHUB_ENV
            -   name: 'Copy Server Launch Script (Windows)'
                run: |
                    cp StarMade-dedicated-server-windows.bat StarMade-Launcher-Windows/StarMade-dedicated-server-windows.bat
            -   name: 'Copy Server Launch Script (Linux)'
                run: |
                    cp StarMade-dedicated-server-linux.sh StarMade-Launcher-Linux/StarMade-dedicated-server-linux.sh
            -   name: 'Copy Server Launch Script (MacOS)'
                run: |
                    cp StarMade-dedicated-server-macos.command StarMade-Launcher-MacOS/StarMade-dedicated-server-macos.command
            -   name: 'Create Launcher Directory (Windows)'
                run: |
                    mkdir StarMade-Launcher-Windows/StarMade
            -   name: 'Create Launcher Directory (Linux)'
                run: |
                    mkdir StarMade-Launcher-Linux/StarMade
            -   name: 'Create Launcher Directory (MacOS)'
                run: |
                    mkdir StarMade-Launcher-MacOS/StarMade
            -   name: 'List Files'
                run: |
                    ls -la ./
            -   name: 'Unzip JRE8 (Windows)'
                run: |
                    unzip -o java/Windows/jre8.zip -d StarMade-Launcher-Windows/StarMade
            -   name: 'Unzip JRE8 (Linux)'
                run: |
                    unzip -o java/Linux/jre8.zip -d StarMade-Launcher-Linux/StarMade
            -   name: 'Unzip JRE8 (MacOS)'
                run: |
                    unzip -o java/MacOS/jre8.zip -d StarMade-Launcher-MacOS/StarMade
            -   name: 'Unzip JRE23 (Windows)'
                run: |
                    unzip -o java/Windows/jre23.zip -d StarMade-Launcher-Windows/StarMade
            -   name: 'Unzip JRE23 (Linux)'
                run: |
                    unzip -o java/Linux/jre23.zip -d StarMade-Launcher-Linux/StarMade
            -   name: 'Unzip JRE23 (MacOS)'
                run: |
                    unzip -o java/MacOS/jre23.zip -d StarMade-Launcher-MacOS/StarMade
            -   name: 'Create Linux Archive'
                run: |
                    zip -r StarMade-Launcher-Linux.zip StarMade-Launcher-Linux
            -   name: 'Create Windows Archive'
                run: |
                    zip -r StarMade-Launcher-Windows.zip StarMade-Launcher-Windows
            -   name: 'Create MacOS Archive'
                run: |
                    zip -r StarMade-Launcher-MacOS.zip StarMade-Launcher-MacOS
            -   name: 'Create Release'
                id: create_release
                uses: actions/create-release@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: v${{ env.VERSION }}
                    release_name: v${{ env.VERSION }}
                    draft: true
                    prerelease: false
            -   name: 'Upload Release Asset (Linux)'
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ steps.create_release.outputs.upload_url }}
                    asset_path: StarMade-Launcher-Linux.zip
                    asset_name: StarMade-Launcher-Linux.zip
                    asset_content_type: application/zip
            -   name: 'Upload Release Asset (Windows)'
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ steps.create_release.outputs.upload_url }}
                    asset_path: StarMade-Launcher-Windows.zip
                    asset_name: StarMade-Launcher-Windows.zip
                    asset_content_type: application/zip
            -   name: 'Upload Release Asset (MacOS)'
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ steps.create_release.outputs.upload_url }}
                    asset_path: StarMade-Launcher-MacOS.zip
                    asset_name: StarMade-Launcher-MacOS.zip
                    asset_content_type: application/zip