name: Package
on: [ push ]
jobs:
    build-executables:
        name: 'Build ${{ matrix.os }} Executable'
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ macos-latest, windows-latest, ubuntu-latest ]
        steps:
            -   name: 'Checkout'
                uses: actions/checkout@v3
            -   name: 'Setup Java 18'
                uses: actions/setup-java@v1
                with:
                    java-version: 18
            -   name: 'Build Executable'
                run: |
                    ./gradlew package
            -   name: 'Get Version Number'
                run: |
                    echo "VERSION=$(./gradlew properties -q | grep "version: " | awk '{print $2}')" >> $GITHUB_ENV
    debug:
        name: 'Debug'
        runs-on: ubuntu-latest
        steps:
            -   name: 'List Files'
                run: |
                    ls -la
    create-windows-archive:
        name: 'Create Windows Archive'
        runs-on: windows-latest
        needs: [ debug, build-executables ]
        steps:
            -   name: 'Checkout'
                uses: actions/checkout@v3
            -   name: 'Zip Windows Executable'
                run: |
                    powershell Compress-Archive ./release-builds/windows ./StarMade-Launcher_Windows.zip
            -   name: 'Publish Windows Executable'
                uses: actions/upload-artifact@v2-preview
                with:
                    name: StarMade-Launcher (Windows)
                    path: StarMade-Launcher_Windows.zip
    create-macos-archive:
        name: 'Create MacOS Archive'
        runs-on: macos-latest
        needs: [ debug, build-executables ]
        steps:
            -   name: 'Checkout'
                uses: actions/checkout@v3
            -   name: 'Zip MacOS Executable'
                run: |
                    zip -r StarMade-Launcher_MacOS.zip ./release-builds/macos
            -   name: 'Publish MacOS Executable'
                uses: actions/upload-artifact@v2-preview
                with:
                    name: StarMade-Launcher (MacOS)
                    path: StarMade-Launcher_MacOS.zip
    create-linux-archive:
        name: 'Create Linux Archive'
        runs-on: ubuntu-latest
        needs: [ debug, build-executables ]
        steps:
            -   name: 'Checkout'
                uses: actions/checkout@v3
            -   name: 'Zip Linux Executable'
                run: |
                    zip -r StarMade-Launcher_Linux.zip ./release-builds/linux
            -   name: 'Publish Linux Executable'
                uses: actions/upload-artifact@v2-preview
                with:
                    name: StarMade-Launcher (Linux)
                    path: StarMade-Launcher_Linux.zip
    create-release:
        name: 'Create Release'
        runs-on: ubuntu-latest
        needs: [ create-windows-archive, create-macos-archive, create-linux-archive ]
        steps:
            -   name: 'Checkout'
                uses: actions/checkout@v3
            -   name: 'Create Release'
                id: create_release
                uses: actions/create-release@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ env.VERSION }}
                    release_name: ${{ env.VERSION }}
                    draft: true
                    prerelease: false
            -   name: 'Upload Release Asset (Windows)'
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ steps.create-release.outputs.upload_url }}
                    asset_path: StarMade-Launcher_Windows.zip
                    asset_name: StarMade-Launcher_Windows.zip
                    asset_content_type: application/zip
            -   name: 'Upload Release Asset (MacOS)'
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ steps.create-release.outputs.upload_url }}
                    asset_path: StarMade-Launcher_MacOS.zip
                    asset_name: StarMade-Launcher_MacOS.zip
                    asset_content_type: application/zip
            -   name: 'Upload Release Asset (Linux)'
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ steps.create-release.outputs.upload_url }}
                    asset_path: StarMade-Launcher_Linux.zip
                    asset_name: StarMade-Launcher_Linux.zip
                    asset_content_type: application/zip