name: Package
on: [ push ]
jobs:
  build-executables:
    name: 'Build ${{ matrix.os }} Executable'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Setup Java 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Build Executable'
        run: |
          ./gradlew jpackage
      - name: 'Get Version Number'
        run: |
          echo "VERSION=$(./gradlew properties -q | grep "version: " | awk '{print $2}')" >> $GITHUB_ENV
      - name: 'Zip ${{ matrix.os }} Executable' # There will be a StarMade-Launcher folder at ./release-builds/StarMade-Launcher-${{ matrix.os }}/
        run: |
          mkdir -p release-builds/StarMade-Launcher-${{ matrix.os }}
          cp -r build/jpackage/StarMadeLauncher/* release-builds/StarMade-Launcher-${{ matrix.os }}
          zip -r StarMade-Launcher-${{ matrix.os }}.zip release-builds/StarMade-Launcher-${{ matrix.os }}
      - name: 'Publish Executable'
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'StarMade-Launcher-${{ matrix.os }}.zip'