name: Package
on: [ push ]
jobs:
    build-executables:
        name: 'Build ${{ matrix.os }} Executable'
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ macos-latest, windows-latest, ubuntu-latest ]
        steps:
            -   name: 'Checkout'
                uses: actions/checkout@v3
            -   name: 'Setup Java 18'
                uses: actions/setup-java@v1
                with:
                    java-version: 18
            -   name: 'Build Executable'
                run: |
                    ./gradlew package
            -   name: 'Get Version Number'
                run: |
                    echo "VERSION=$(./gradlew properties -q | grep "version: " | awk '{print $2}')" >> $GITHUB_ENV
            -   name: 'List Files'
                run: |
                    ls -la
            -   name: 'Create Windows Archive'
                run: |
                    if [ ${{ matrix.os }} == 'windows-latest' ]; then
                        powershell Compress-Archive ./release-builds/windows ./StarMade-Launcher_Windows.zip
                    fi
            -   name: 'Create MacOS Archive'
                run: |
                    if [ ${{ matrix.os }} == 'macos-latest' ]; then
                        zip -r StarMade-Launcher_MacOS.zip ./release-builds/macos
                    fi
            -   name: 'Create Linux Archive'
                run: |
                    if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
                        zip -r StarMade-Launcher_Linux.zip ./release-builds/linux
                    fi
            -   name: 'Publish Windows Executable'
                uses: actions/upload-artifact@v2-preview
                with:
                    name: StarMade-Launcher (Windows)
                    path: StarMade-Launcher_Windows.zip
            -   name: 'Publish MacOS Executable'
                uses: actions/upload-artifact@v2-preview
                with:
                    name: StarMade-Launcher (MacOS)
                    path: StarMade-Launcher_MacOS.zip
            -   name: 'Publish Linux Executable'
                uses: actions/upload-artifact@v2-preview
                with:
                    name: StarMade-Launcher (Linux)
                    path: StarMade-Launcher_Linux.zip
            -   name: 'Set Version Number'
                run: |
                    echo "VERSION=$(./gradlew properties -q | grep "version: " | awk '{print $2}')" >> $GITHUB_ENV
            -   name: 'Create Release'
                id: create_release
                uses: actions/create-release@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ env.VERSION }}
                    release_name: ${{ env.VERSION }}
                    draft: true
                    prerelease: false
            -   name: 'Upload Release Asset (Windows)'
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ steps.create_release.outputs.upload_url }}
                    asset_path: StarMade-Launcher_Windows.zip
                    asset_name: StarMade-Launcher_Windows.zip
                    asset_content_type: application/zip
            -   name: 'Upload Release Asset (MacOS)'
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ steps.create_release.outputs.upload_url }}
                    asset_path: StarMade-Launcher_MacOS.zip
                    asset_name: StarMade-Launcher_MacOS.zip
                    asset_content_type: application/zip
            -   name: 'Upload Release Asset (Linux)'
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ steps.create_release.outputs.upload_url }}
                    asset_path: StarMade-Launcher_Linux.zip
                    asset_name: StarMade-Launcher_Linux.zip
                    asset_content_type: application/zip